config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/index'
  root to: 'home#index'

  get 'physicians' => 'physicians#index', as: :index_physician

  get 'physicians/new' => 'physicians#new', as: :new_physician

  post 'physicians/create' => 'physicians#create', as: :create_physician

  get 'physicians/:id' => 'physicians#show', as: :physician

  get 'physicians/:id/edit' => 'physicians#edit', as: :edit_physician

  patch 'physicians/:id/update' => 'physicians#update', as: :update_physician

  get 'physicians/search' => 'physicians#search'

  delete 'physicians/:id/delete' => 'physicians#destroy', as: :destroy_physician

  get 'pillboxes' => 'pillboxes#index', as: :index_pillbox

  get 'pillboxes/new' => 'pillboxes#new', as: :new_pillbox

  post 'pillboxes/create' => 'pillboxes#create', as: :create_pillbox

  get 'pillboxes/:id' => 'pillboxes#show', as: :pillbox

  get 'pillboxes/:id/edit/' => 'pillboxes#edit', as: :edit_pillbox

  patch 'pillboxes/:id/update' => 'pillboxes#update', as: :update_pillbox

  get 'pillboxes/search' => 'pillboxes#search'

  delete 'pillboxes/:id/delete/' => 'pillboxes#destroy', as: :destroy_pillbox

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :pillboxes, :through => :users
end

app/models/pillbox.rb
class Pillbox < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pillboxes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:f_name, :l_name, :username, :address_line_one, :address_line_two, :city, :state, :zip, :country, :phone_number, :date_of_birth, :gender])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! # Must be logged in to access the home page
  def index
    @users = User.where(id: current_user.id)
    @pillboxes = Pillbox.where(user_id: current_user.id)
    @physicians = Physician.where(user_id: current_user.id)
  end


end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
    before_action :authenticate_user! # Must be logged in to access the physician page
  def index
    @physicians = Physician.where(user_id: current_user.id)
    @users = User.where(id: current_user.id)
  end

  def show
    @physician = Physician.find(params[:id])
    @users = User.where(id: current_user.id)
  end

  def new
    @physician = Physician.new
    @users = User.where(id: current_user.id)
  end

  def create
    @physician = Physician.new(physician_params)
    if @physician.save
      redirect_to home_index_path
    else
      render :new
    end
  end

  def edit
    @physician = Physician.find(params[:id])
    @users = User.where(id: current_user.id)
  end

  def update
    @physician = Physician.find(params[:id])
    if @physician.update_attributes(physician_params)
      redirect_to home_index_path
    else
      render :edit
    end
  end

  def search
  end

  def destroy
    @physician = Physician.find(params[:id]).destroy
    redirect_to home_index_path
  end

  def physician_params
    params.require(:physician).permit(:title, :f_name, :l_name, :specialty, :address_line_one, :address_line_two, :city, :state, :zip, :country, :phone_number, :email, :user_id)
  end
end

app/controllers/pillboxes_controller.rb
class PillboxesController < ApplicationController
  before_action :authenticate_user! # Must be logged in to access the pillbox page
  def index
    @pillboxes = Pillbox.where(user_id: current_user.id)
    @users = User.where(id: current_user.id)
  end

  def show
    @pillbox = Pillbox.find(params[:id])
    @users = User.where(id: current_user.id)
  end

  def new
    @pillbox = Pillbox.new
    @users = User.where(id: current_user.id)
  end

  def create
    @pillbox = Pillbox.new(pillbox_params)
    if @pillbox.save
      redirect_to home_index_path
    else
      render :new
    end
  end

  def edit
    @pillbox = Pillbox.find(params[:id])
    @users = User.where(id: current_user.id)
  end

  def update
    @pillbox = Pillbox.find(params[:id])
    if @pillbox.update_attributes(pillbox_params)
      redirect_to home_index_path
    else
      render :edit
    end
  end

  def search
  end

  def destroy
    @pillbox = Pillbox.find(params[:id]).destroy
    redirect_to home_index_path
  end

  def pillbox_params
    params.require(:pillbox).permit(:user_id, :medication_name, :dosage, :frequency, :route, :indication, :prescribing_physician)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/pillboxes_helper.rb
module PillboxesHelper
end

app/views/home/index.html.erb
<!-- Index/Profile Page -->
<div class="clearfix">
<nav class="profile_navbar">
  <div class="title_profile">
    <div class="font_style">
      <h1 style="font-size: 40px;">user<i class="fa fa-user-md" aria-hidden="true"></i></h1>
    </div>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>
<br>
<%= link_to "Create.pill", new_pillbox_path %><br>
<%= link_to "Show.Pillbox", index_pillbox_path %><br>
<%= link_to "Create.Physician", new_physician_path %><br>
<%= link_to "Show.Physicians", index_physician_path %><br>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

<div class="big_pillbox">
  <div class="profile_pillbox">
    <h1>pill.box <i class="fa fa-medkit" aria-hidden="true"></i></h1>
  </div>
  <div class="row_pillbox">
    <% @pillboxes.each do |f| %>
    <div class="col-md-3">
      <div class="pillbox">
            <strong>Medication: </strong><%= f.medication_name %><br>
            <strong>Dosage: </strong><%= f.dosage %><br>
            <strong>Frequency: </strong><%= f.frequency %><br>
            <strong>Route: </strong><%= f.route %><br>
            <strong>Indication: </strong><%= f.indication %><br>
            <strong>Prescribing Physician: </strong><%= f.prescribing_physician %><br>
            <%= link_to "Show Pillbox", pillbox_path(f.id) %><br>
            <%= link_to "Delete Pillbox", destroy_pillbox_path(f.id), :method => :delete %>
        </div>
        <br>
      </div>
  <% end %>
</div>
</div>

<div class="big_physician">
  <div class="profile_physician">
    <h1>physicians <i class="fa fa-stethoscope" aria-hidden="true"></i></h1>
  </div>
  <div class="row_physician">
    <% @physicians.each do |f| %>
    <div class="col-md-3">
      <div class="physician">
          <%= f.title %>,
          <%= f.f_name %>
          <%= f.l_name %><br>
          <strong>Specialty: </strong><%= f.specialty %><br>
          <strong>Address: </strong><%= f.address_line_one %><%= f.address_line_two %><br>
          <%= f.city %>, <%= f.state %> <%= f.zip %><br>
          <%= f.country %><br>
          <strong>Phone Number: </strong><%= f.phone_number %><br>
          <strong>Email: </strong><%= f.email %><br>
          <%= link_to "Show Physician", physician_path(f.id) %><br>
          <%= link_to "Delete Physician", destroy_physician_path(f.id), :method => :delete %>
          </div>
          <br>
        </div>
    <% end %>
  </section>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualPillbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" text="text/css" href='/main.css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
  <link href="main.css" rel="stylesheet" media="all and (max-width: 1024px)">
</head>
<body>
  <!-- <div class="sign_out">
    <% if user_signed_in? %>
        Signed in as <%= current_user.f_name %>.
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <% end %>
  </div> -->
<%= yield %>
<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/physicians/create.html.erb
<h1>Physicians#create</h1>
<p>Find me in app/views/physicians/create.html.erb</p>

app/views/physicians/destroy.html.erb
<h1>Physicians#delete</h1>
<p>Find me in app/views/physicians/destroy.html.erb</p>

app/views/physicians/edit.html.erb
<!-- Edit Physician -->
<div class="clearfix">
<nav class="physician_navbar">
  <div class="title_physician">
    <h1 style="font-size: 40px;">edit physician</h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>
<br>
<%= link_to "Profile", home_index_path %><br>
<%= link_to "Create.Pill", new_pillbox_path %><br>
<%= link_to "Show.Pillbox", index_pillbox_path %><br>
<%= link_to "Create.Physician", new_physician_path %><br>
<%= link_to "Show.Physicians", index_physician_path %><br>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

  <br>
<div class="create_physician">
  <div class="row_physician">
    <h1>physicians  <i class="fa fa-stethoscope" aria-hidden="true"></i></h1>
<%= form_for(@physician, url: update_physician_path) do |f| %>
<div class="col-md-12">
<div class="field">
 <%= f.label :title, "Title: " %>
 <span class="option">DR <span><%= f.radio_button :title, "DR" %>
 <span class="option">PA <span><%= f.radio_button :title, "PA" %>
 <span class="option">NP <span><%= f.radio_button :title, "NP" %>
</div>

<div class="field">
  <%= f.label :f_name, "First Name: " %>
  <%= f.text_field :f_name %>
  <%= f.label :l_name, "Last Name: " %>
  <%= f.text_field :l_name %>
  <%= f.label :specialty, "Specialty: " %>
  <%= f.text_field :specialty %>
</div>
<div class="field">
  <%= f.label :address_line_one, "Address Line One: " %>
  <%= f.text_field :address_line_one %>
</div>
<div class="field">
  <%= f.label :address_line_two, "Address Line Two: " %>
  <%= f.text_field :address_line_two %>
</div>
<div class="field">
  <%= f.label :city, "City: " %>
  <%= f.text_field :city %>
  <%= f.label :state, "State: " %>
  <%= f.text_field :state %>
</div>

<div class="field">
  <%= f.label :zip, "Zip: " %>
  <%= f.text_field :zip %>
  <%= f.label :country, "Country: " %>
  <%= f.text_field :country %>
</div>

<div class="field">
  <%= f.label :phone_number, "Phone Number: " %>
  <%= f.telephone_field :phone_number %>
  <%= f.label :email, "Email: " %>
  <%= f.email_field :email %>
</div>

<%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit "Update Physician" %>
  </div>
</div>
<% end %>
  </div>
</div>

app/views/physicians/index.html.erb
<!-- Show All Physicians -->
<div class="clearfix">
<nav class="physician_navbar">
  <div class="title_physician">
    <h1 style="font-size: 40px;">show physicians</h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>
<br>
<%= link_to "Profile", home_index_path %><br>
<%= link_to "Create.Pill", new_pillbox_path %><br>
<%= link_to "Show.Pillbox", index_pillbox_path %><br>
<%= link_to "Create.Physician", new_physician_path %><br>
<%= link_to "Show.Physicians", index_physician_path %><br>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

<div class="big_physician">
  <div class="row_physician">
    <h1>physicians  <i class="fa fa-stethoscope" aria-hidden="true"></i></h1>
<% @physicians.each do |f| %>
<div class="col-md-3">
  <br>
  <%= f.title %>,
  <%= f.f_name %>
  <%= f.l_name %><br>
  <strong>Specialty: </strong><%= f.specialty %><br>
  <strong>Address: </strong><%= f.address_line_one %><%= f.address_line_two %><br>
  <%= f.city %>, <%= f.state %> <%= f.zip %><br>
  <%= f.country %><br>
  <strong>Phone Number: </strong><%= f.phone_number %><br>
  <strong>Email: </strong><%= f.email %><br>

    <%= link_to "Edit Physician", edit_physician_path(f.id) %><br>
    <%= link_to "Delete Physician", destroy_physician_path(f.id), :method => :delete %>
  </div>
<% end %>
  </div>
</div>

app/views/physicians/new.html.erb
<!-- Create Physician -->
<div class="clearfix">
<nav class="physician_navbar">
  <div class="title_physician>">
    <h1 style="font-size: 40px;">new physician</h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>
<br>
<%= link_to "Profile", home_index_path %><br>
<%= link_to "Create.Pill", new_pillbox_path %><br>
<%= link_to "Show.Pillbox", index_pillbox_path %><br>
<%= link_to "Create.Physician", new_physician_path %><br>
<%= link_to "Show.Physicians", index_physician_path %><br>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

  <br>
<div class="create_physician">
  <div class="row_physician">
    <div class="col-md-12">
      <h1>physician  <i class="fa fa-stethoscope" aria-hidden="true"></i></h1>
<%= form_for(@physician, url: create_physician_path) do |f| %>
  <div class="field">
   <%= f.label :title, "Title: " %>
   <span class="option">DR <span><%= f.radio_button :title, "DR" %>
   <span class="option">PA <span><%= f.radio_button :title, "PA" %>
   <span class="option">NP <span><%= f.radio_button :title, "NP" %>
  </div>

  <div class="field">
    <%= f.label :f_name, "First Name: " %>
    <%= f.text_field :f_name %>
    <%= f.label :l_name, "Last Name: " %>
    <%= f.text_field :l_name %>
    <%= f.label :specialty, "Specialty: " %>
    <%= f.text_field :specialty %>
  </div>
  <div class="field">
    <%= f.label :address_line_one, "Address Line One: " %>
    <%= f.text_field :address_line_one %>
  </div>
  <div class="field">
    <%= f.label :address_line_two, "Address Line Two: " %>
    <%= f.text_field :address_line_two %>
  </div>
  <div class="field">
    <%= f.label :city, "City: " %>
    <%= f.text_field :city %>
    <%= f.label :state, "State: " %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip, "Zip: " %>
    <%= f.text_field :zip %>
    <%= f.label :country, "Country: " %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :phone_number, "Phone Number: " %>
    <%= f.telephone_field :phone_number %>
    <%= f.label :email, "Email: " %>
    <%= f.email_field :email %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit "Create a Physician" %>
  </div>
</div>
<% end %>
  </div>
</div>

app/views/physicians/search.html.erb
<h1>Physicians#search</h1>
<p>Find me in app/views/physicians/search.html.erb</p>

app/views/physicians/show.html.erb
<!-- Show Physician/:id -->
<div class="clearfix">
<nav class="physician_navbar">
  <div class="title_physician">
    <h1 style="font-size: 40px;"><%= @physician.title %><br><%= @physician.f_name %><br><%= @physician.l_name %></h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>
<br>
<%= link_to "Profile", home_index_path %><br>
<%= link_to "Create.Pill", new_pillbox_path %><br>
<%= link_to "Show.Pillbox", index_pillbox_path %><br>
<%= link_to "Create.Physician", new_physician_path %><br>
<%= link_to "Show.Physicians", index_physician_path %><br>
<%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

  <br>
<div class="create_physician">
  <div class="row_physician">
    <div class="col-md-4">
      <h1>physicians  <i class="fa fa-stethoscope" aria-hidden="true"></i></h1>
      <%= @physician.title %>,
      <%= @physician.f_name %>
      <%= @physician.l_name %><br>
      <strong>Specialty: </strong><%= @physician.specialty %><br>
      <strong>Address: </strong><%= @physician.address_line_one %><%= @physician.address_line_two %><br>
      <%= @physician.city %>, <%= @physician.state %> <%= @physician.zip %><br>
      <%= @physician.country %><br>
      <strong>Phone Number: </strong><%= @physician.phone_number %><br>
      <strong>Email: </strong><%= @physician.email %><br>

  <%= link_to "Edit Physician", edit_physician_path(@physician.id) %><br>
  <%= link_to "Delete Physician", destroy_physician_path, :method => :delete %>
      </div>
    </div>
</div>

app/views/physicians/update.html.erb
<h1>Physicians#update</h1>
<p>Find me in app/views/physicians/update.html.erb</p>

app/views/pillboxes/create.html.erb
<h1>Pillboxes#create</h1>
<p>Find me in app/views/pillboxes/create.html.erb</p>

app/views/pillboxes/destroy.html.erb
<h1>Pillboxes#destroy</h1>
<p>Find me in app/views/pillboxes/destroy.html.erb</p>

app/views/pillboxes/edit.html.erb
<nav class="pillbox_navbar">
  <div class="title_pillbox">
  <h1 style="font-size: 40px;">edit pillbox</h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>

  <%= link_to "Profile", home_index_path %><br>
  <%= link_to "Create.Pill", new_pillbox_path %><br>
  <%= link_to "Show.Pillbox", index_pillbox_path %><br>
  <%= link_to "Create.Physician", new_physician_path %><br>
  <%= link_to "Show.Physicians", index_physician_path %><br>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

  <br>
<div class="create_pillbox">
  <div class="row_pillbox">
    <h1>pill.box <i class="fa fa-medkit" aria-hidden="true"></i></h1>
<%= form_for(@pillbox, url: update_pillbox_path) do |f| %>
  <div class="col-md-12">
  <div class="field">
    <%= f.label :medication_name, "Medication: " %>
    <%= f.text_field :medication_name %>
  </div>
  <div class="field">
    <%= f.label :dosage, "Dosage: " %>
    <%= f.text_field :dosage %>
  </div>
  <div class="field">
    <%= f.label :frequency, "Frequency: " %>
    <%= f.text_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :route, "Route: " %>
    <span class="option">Oral <span><%= f.radio_button :route, "Oral" %>
    <span class="option">Intravenous <span><%= f.radio_button :route, "IV" %>
    <span class="option">Rectal <span><%= f.radio_button :route, "Rectal" %>
    <span class="option">Sublingual <span><%= f.radio_button :route, "Sublingual" %>
    <span class="option">Inhalation <span><%= f.radio_button :route, "Inhalation" %>
    <span class="option">Intramuscular (IM) <span><%= f.radio_button :route, "Intramuscular" %>
    <span class="option">Subcutaneous (SQ) <span><%= f.radio_button :route, "Subcutaneous" %>
  </div>
  <div class="field">
    <%= f.label :indication, "Indication: " %>
    <%= f.text_field :indication %>
  </div>
  <div class="field">
    <%= f.label :prescribing_physician, "Prescribing Physician: " %>
    <%= f.text_field :prescribing_physician %>
  </div>

  <div class="actions">
    <%= f.submit "Update Pillbox" %>
  </div>
</div>
<% end %>
  </div>
</div>

app/views/pillboxes/index.html.erb
<nav class="pillbox_navbar">
  <div class="title_pillbox">
  <h1 style="font-size: 40px;">show pillbox</h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>

  <%= link_to "Profile", home_index_path %><br>
  <%= link_to "Create.Pill", new_pillbox_path %><br>
  <%= link_to "Show.Pillbox", index_pillbox_path %><br>
  <%= link_to "Create.Physician", new_physician_path %><br>
  <%= link_to "Show.Physicians", index_physician_path %><br>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>
<div class="big_pillbox">
  <div class="row_pillbox">
    <h1>pill.box <i class="fa fa-medkit" aria-hidden="true"></i></h1>
  <% @pillboxes.each do |f| %>
  <div class="col-md-3">
<br>
  <strong>Medication: </strong><%= f.medication_name %><br>
  <strong>Dosage: </strong><%= f.dosage %>mg<br>
  <strong>Frequency: </strong><%= f.frequency %>x daily<br>
  <strong>Route: </strong><%= f.route %><br>
  <strong>Indication: </strong><%= f.indication %><br>
  <strong>Prescribing Physician: </strong><%= f.prescribing_physician %><br>

    <%= link_to "Edit Pillbox", edit_pillbox_path(f.id) %><br>
    <%= link_to "Delete Pillbox", destroy_pillbox_path(f.id), :method => :delete %>
  </div>
<% end %>
  </div>
</div>

app/views/pillboxes/new.html.erb
<nav class="pillbox_navbar">
  <div class="title_pillbox">
  <h1 style="font-size: 40px;">create a pill</h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>

  <%= link_to "Profile", home_index_path %><br>
  <%= link_to "Create.Pill", new_pillbox_path %><br>
  <%= link_to "Show.Pillbox", index_pillbox_path %><br>
  <%= link_to "Create.Physician", new_physician_path %><br>
  <%= link_to "Show.Physicians", index_physician_path %><br>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

  <br>
<div class="create_pillbox">
    <div class="row_pillbox">
      <h1>pill  <i class="fa fa-medkit" aria-hidden="true"></i></h1>
  <%= form_for(@pillbox, url: create_pillbox_path) do |f| %>
  <div class="col-md-12">
    <div class="field">
      <%= f.label :medication_name, "Medication: " %>
      <%= f.text_field :medication_name %>
    </div>
    <div class="field">
      <%= f.label :dosage, "Dosage: " %>
      <%= f.text_field :dosage %>
    </div>
    <div class="field">
      <%= f.label :frequency, "Frequency: " %>
      <%= f.text_field :frequency %>
    </div>
    <div class="field">
      <%= f.label :route, "Route: " %>
      <span class="option">Oral <span><%= f.radio_button :route, "Oral" %>
      <span class="option">Intravenous <span><%= f.radio_button :route, "IV" %>
      <span class="option">Rectal <span><%= f.radio_button :route, "Rectal" %>
      <span class="option">Sublingual <span><%= f.radio_button :route, "Sublingual" %>
      <span class="option">Inhalation <span><%= f.radio_button :route, "Inhalation" %>
      <span class="option">Intramuscular (IM) <span><%= f.radio_button :route, "Intramuscular" %>
      <span class="option">Subcutaneous (SQ) <span><%= f.radio_button :route, "Subcutaneous" %>
    </div>

    <div class="field">
      <%= f.label :indication, "Indication: " %>
      <%= f.text_field :indication %>
    </div>
    <div class="field">
      <%= f.label :prescribing_physician, "Prescribing Physician: " %>
      <%= f.text_field :prescribing_physician %>
    </div>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="actions">
      <%= f.submit "Create Pillbox" %>
    </div>
  </div>
  <% end %>
      </div>
    </div>

app/views/pillboxes/search.html.erb
<h1>Pillboxes#search</h1>
<p>Find me in app/views/pillboxes/search.html.erb</p>

app/views/pillboxes/show.html.erb
<nav class="pillbox_navbar">
  <div class="title_pillbox">
  <h1 style="font-size: 40px;"><%= @pillbox.medication_name %></h1>
    <% @users.each do |user| %>
        <%= user.f_name %>
        <%= user.l_name %>
    <% end %>
  </div>

  <%= link_to "Profile", home_index_path %><br>
  <%= link_to "Create.Pill", new_pillbox_path %><br>
  <%= link_to "Show.Pillbox", index_pillbox_path %><br>
  <%= link_to "Create.Physician", new_physician_path %><br>
  <%= link_to "Show.Physicians", index_physician_path %><br>
  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %><br>
</nav>

<div class="create_pillbox">
  <div class="row_pillbox">
    <div class="col-md-4">
      <h1>pill.box <i class="fa fa-medkit" aria-hidden="true"></i></h1>
<strong>Medication: </strong><%= @pillbox.medication_name %><br>
<strong>Dosage: </strong><%= @pillbox.dosage %><br>
<strong>Frequency: </strong><%= @pillbox.frequency %><br>
<strong>Route: </strong><%= @pillbox.route %><br>
<strong>Indication: </strong><%= @pillbox.indication %><br>
<strong>Prescribing Physician: </strong><%= @pillbox.prescribing_physician %><br>

<%= link_to "Edit Pillbox", edit_pillbox_path(@pillbox.id) %><br>
<%= link_to "Delete Pillbox", destroy_pillbox_path, :method => :delete %>
    </div>
  </div>
</div>

app/views/pillboxes/update.html.erb
<h1>Pillboxes#update</h1>
<p>Find me in app/views/pillboxes/update.html.erb</p>